Generating integrations manifests from github workflows for manual de…
coralogix/eng-integrations pull request #47
Opened 2022-04-24 12:33 UTC by amit-mazor

As part of the GitHub Actions worfklows runs, the desired integration's manifests will be generated using the CX-Integrations CLI, and will be saved under 'manual-manifests/<integration-name>'. 

* By adding the generation of the yamls inside the workflows, we can be sure we always have the most updated yamls that match the last release.

* If any configuration change, or env var change is required, it will be done manually on these yamls.  

* The generated yamls are only for 'fluentd-http' and 'fluent-bit-http' since the CLI supports only these two. The Coralogix integrations are going to be deprecated, therefore it's not supported here.

2022-04-26 11:52 UTC, avivgold098 requested changes
Publish the artifacts after the `generate` command

2022-04-27 09:00 UTC, avivgold098 requested changes
@amit-mazor There is not an available plugin to upload files during the steps? I less like this workflow.
Don't forget there is protection on master which required the one approval, then we should look for something which is more github workflow native

2022-11-10 11:54 UTC, amit-mazor commented
@avivgold098 do we want to keep working on it ? or should I close it ?

2022-11-10 13:14 UTC, avivgold098 commented
@amit-mazor close

2022-11-10 13:17 UTC, closed without merging