FIX: fluentd buffer configuration and fluentbit set retry no limit, c…
coralogix/eng-integrations pull request #48
Opened 2022-04-25 13:52 UTC by amit-mazor

## Fixes and Updates:

* set `logLevel` on 'error' instead of 'info' in **all integrations**. 
* set default values in **fluentd-http** README `override file example`.
* set `Retry_Limit` in **Fluent-bit** to no limit in order for it to keep retrying and not lose any data 
* update **Fluentd** `overflow_action` to 'throw_exception' instead of 'block' 
* set **Fluentd** `flush_thread_count` to 4 for parallelism of the outputs

2022-04-25 14:00 UTC, oded-dd submitted a review, later dismissed

2022-04-25 16:51 UTC, talknopf approved these changes

2022-04-26 12:06 UTC, avivgold098 requested changes
1. Please update the changelog 
2. In-depth docs should keep outside the main readme  
3. Endpoints should document either in each integration or in the root README

2022-04-26 12:06 UTC, avivgold098 commented on fluentd/http/README.md
> +                                2,
Should move to docs under `fluentd`

2022-04-27 09:05 UTC, avivgold098 requested changes
Please upadte endpoints

2022-04-27 10:13 UTC, avivgold098 approved these changes

2022-04-27 11:07 UTC, merged