FIX: disabling metrics and logs pipeline, update READMEs
coralogix/eng-integrations pull request #80
Opened 2022-08-24 13:54 UTC by amit-mazor

## FIXES and UPGRADES:

* Update `main readme` to include the new otel chart in addition to the fluent charts and add some small fixes
* Update `otel-agent readme`, to get some info from the main readme
* Update the agent `installation command` - after some checks, its impossible to use `--set` to override only specific envs, it requires to set the whole envs in the installation command which is very complicated. 
Therefore, it requires to create an `override.yaml` file which includes all of the envs in order to change an env.
* Update the otel-agent secret to be the same secret as the fluent charts secret, so there is no need now to have two secrets for logs and traces, with the same key inside. 
* Changed the `pipeline order` - now metrics and logs are null [disabled] in the pipeline `after the traces section`. By having them before the tracing, the are enabled automatically, so the order affects it.

2022-08-24 14:05 UTC, avivgold098 requested changes
@amit-mazor make changelog, also please move the charts to folder call `charts` so it will be separated from the example. I think it will require also update the github action paths

2022-08-24 14:07 UTC, amit-mazor commented
@avivgold098 The issue with the changelog is that it hasn't been updated since a long time ago, there are 6 new versions here of Fluentbit for example, that are not documented in the changelog. 
So I think it should be updated before adding this new release

2022-08-24 14:23 UTC, avivgold098 commented
> check

So lets have specific one for otel

2022-08-24 14:41 UTC, amit-mazor commented
@avivgold098 sounds good, added a new dedicated changelog, its under the opel-agent dir

2022-08-25 08:27 UTC, avivgold098 approved these changes

2022-08-25 08:29 UTC, merged